### ISSUE TITLE
GAPI-Querier (aka find out-of-album photos) Instruction

### ISSUE THREAD

**Issue by dcschris** [jonagh/gapi-querier#8]
Hi Jonagh,

Sorry, maybe it's me, but I couldn't follow the instructions on the readme page for the GAPI-Querier (aka find out-of-album photos) API. Perhaps Google has changed the way they organise things or changed their GUI. Could you confirm whether these instructions are accurate or please update them so they can be followed. I'm really keen to try this API out

Thanks
C

**Comment by jonagh** [comment]
I just adjusted the instructions with some minor improvements for clarity, however there were no significant changes to the Google Developer Console (apart from needing to click Edit App in the initial consent screen page to get to the needed settings).

If you could tell me where you're getting stuck, maybe I can provide more information.

**Comment by dcschris** [comment]
Hi Jonagh
Thanks for the additional instructions, they helped somewhat and I was able
to try to run the API; however, I got an Error 403 message as below. I
think this may be something to do with, on the OAuth consent screen, I
selected User type External, as Google wouldn't get me chooseInternal. Is
this the issue and, if so, any ideas on how to resolve this.

Thanks again for your prompt help
C

Error message below:

Authorization Error
Error 403: access_denied
The developer hasn’t given you access to this app. It’s currently being
tested and it hasn’t been verified by Google. If you think you should have
access, contact the developer ***@***.***).
Learn more
<https://support.google.com/accounts/answer/3466521?p=app_notverified>
Request Details

   - openid.realm=
   - response_type=permission id_token
   - redirect_uri=storagerelay://https/jonagh.github.io?id=auth732138
   - ss_domain=https://jonagh.github.io
   - client_id=************-
   50anvtksnlohfm0os2fjap5145829lnt.apps.googleusercontent.com
   - fetch_basic_profile=true
   - gsiwebsdk=2
   - access_type=online
   - scope=https://www.googleapis.com/auth/userinfo.email
   https://www.googleapis.com/auth/userinfo.profile openid
   https://www.googleapis.com/auth/photoslibrary.readonly

**Comment by jonagh** [comment]
Ya the Authorization Error is because you haven't verified your domain (see Domain Verification page in google developer console). I personally don't bother verifying since I trust myself, so on that Authorization Error page I just click Advanced and Go to (unsafe)... to bypass the warning. If you want to verify your domain you can do that and it will get rid of that warning.

Also note that ad-blockers/etc might block google auth requests, so that's another problem that you may run into - I just ran into it when re-testing the app and so thought I'd mention it.
