### ISSUE TITLE
Error 403: access_denied

### ISSUE THREAD

**Issue by Jeroen00** [jonagh/gapi-querier#9]
I followed the steps and trying to connect through https://jonagh.github.io/gapi-querier/ but getting below error? 

Error 403: access_denied
The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer

**Comment by jonagh** [comment]
The Google Developer Console has changed and requires different info (compared to what I had in the readme instructions).
I've now updated the readme with better instructions per the new Google Developer Console interface - specifically the "Setup consent screen" section.

I believe in order to fix your 403 problem you need to ensure:
- In the consent-screen settings you should either have the published status as "In production" (published) or if you leave it in "Testing" mode then you must add the "Test user" that you want to use with your app.
- Also, if you are using a Google Workspaces/Business account (instead of a normal Google account), then you should ensure the "User type" setting is set as you desire. I have a Google Workspaces account, I set it to "External" so I can use it with different accounts, but if you are using a normal Google account then I assume this option will not be shown.

I hope that helps/fixes your issue.

**Comment by Jeroen00** [comment]
Thanks, the first bullet solution worked!
